### ISSUE TITLE
Neither Volla nor Sailfish can currently be installed with Ubports

### ISSUE THREAD

**Issue by poetaster** [HelloVolla/local_manifests#3]
See: 
https://github.com/ubports/ubports-installer/issues/1785
and
https://github.com/ubports/ubports-installer/issues/1782

I'm guessing it's something to do with the images being installed, not ubports itself?

**Comment by poetaster** [comment]
Installing ubuntu touch DOES work.

**Comment by JamiKettunen** [comment]
I've not experiences something like that with Volla OS; Sailfish OS however fails to boot because the system partition on the device is used for UBports root filesystem, and SFOS expects it to contain an Android OS so it can start HAL components to initialize display and such.

So to boot Sailfish OS you first need to get a system partition from Volla OS flashed (UBports installer is the easier, but perhaps slowest way).

**Comment by poetaster** [comment]
Hmm. It's a bit of a catch 22. I can't get Volla installed either. That ends in a TWRP boot loop.  That was ticket: https://github.com/ubports/ubports-installer/issues/1782 

I could try adb installing a volla image, but which one ?

**Comment by poetaster** [comment]
probably only this one: volla-9.0-20201019-nightly-k63v2_64_bsp-signed.zip ...?

**Comment by poetaster** [comment]
Ok, just used ubports to install volla, again, and it worked. sigh. I'll post as soon as I've got one further....

**Comment by poetaster** [comment]
Ok, so it seems:
1. If you have Ubuntu Touch installed you must
2.  Frist install an android (Volla) which might require 2 installs (both times I had to do it twice to get aound an twrp boot loop)
3.  Then you can install SFOS.
